import CurrentSitePage from "@/components/CurrentSitePage";
export const metadata={title:'Stucco Siding (EIFS)'+" | CladCan",description:'EIFS, often called synthetic stucco, is a non-load-bearing exterior cladding system combining continuous insulation with a reinforced finish layer for energy efficiency and design flexibility.'};
const supportingNotes = [
  {label:"What it is", text:"EIFS is a non-load-bearing exterior cladding assembly that combines insulation, a reinforced base coat and finish layer to provide a continuous-insulation exterior with a range of finish textures."},
  {label:"Where it fits", text:"EIFS is often used on residential and commercial façades where design flexibility, a smooth finish and a continuous insulation layer are important to the architectural intent."},
  {label:"Selection factors", text:"Drainage strategy, substrate conditions, movement joints, façade detailing and finish compatibility all have a major impact on system performance."},
  {label:"How CladCan helps", text:"CladCan can coordinate system selection, accessory planning and installation sequencing with the actual project assembly and conditions."}
];
export default function Page(){return <CurrentSitePage title={'Stucco Siding (EIFS)'} intro={'EIFS, often called synthetic stucco, is a non-load-bearing exterior cladding system combining continuous insulation with a reinforced finish layer for energy efficiency and design flexibility.'} overview={'EIFS assemblies are often considered for projects that need a continuous insulation layer and a wide range of finish textures, but success depends on how the wall assembly is detailed and installed.'} items={[{title:'EIFS Assemblies',href:'/exterior-systems/stucco-eifs/eifs-assemblies',text:'Continuous-insulation façade assemblies coordinated for envelope performance.'},{title:'Architectural Finishes',href:'/exterior-systems/stucco-eifs/architectural-finishes',text:'A broad range of textures and finish possibilities for residential and commercial design.'},{title:'DuROCK & Sto Systems',href:'/exterior-systems/stucco-eifs/durock-sto',text:"System sourcing and product coordination with established EIFS suppliers such as DuROCK and Sto."}]} decisionSupport={supportingNotes} />;}
