import Link from "next/link";
import { ArrowUpRight, Check, ShieldCheck, Flame, Droplets, Palette } from "lucide-react";
import { aluminumSystems as subcategories } from "@/data/aluminumHierarchy";
import ViewToggleCollection from "@/components/ViewToggleCollection";
export const metadata={title:"Aluminum Siding & Soffit Systems | CladCan",description:"Explore architectural aluminum siding, soffit, battens and woodgrain exterior systems supplied, fabricated and installed by CladCan across Ontario."};

const benefits=[
 {icon:ShieldCheck,title:"Durable",text:"Aluminum is commonly selected where weather resistance, appearance retention and long-term material stability are important considerations."},
 {icon:Flame,title:"Material Choice",text:"Aluminum is often considered for exterior assemblies where a non-combustible or low-combustibility material category is being evaluated."},
 {icon:Droplets,title:"Weather Resistant",text:"Practical for wall, soffit and rainscreen applications exposed to Ontario seasonal weather and changing site conditions."},
 {icon:Palette,title:"Finish Flexibility",text:"Available in multiple architectural finishes, including solid colours and woodgrain-look options depending on the selected system."},
];
const applications=["Residential façades","Custom homes","Multi-residential buildings","Commercial buildings","Soffits and ceilings","Feature walls","Architectural accents","Privacy screens"];
export default function AluminumPage(){return <main className="aluminumPage">
<section className="aluminumPageHero exteriorSystemDetailHero" style={{backgroundImage:"url('/images/exterior-systems/modern-aluminum-siding-soffit-house-ontario.webp')"}}><div className="aluminumPageHeroOverlay"/><div className="wrap aluminumPageHeroContent"><span className="aluminumEyebrow">ALUMINUM SIDING & SOFFIT</span><h1>Architectural aluminum<br/><em>for modern exteriors.</em></h1><p>Durable aluminum siding and soffit systems with clean lines, versatile finishes and dependable exterior performance.</p><div className="aluminumHeroActions"><a href="#systems" className="btn aluminumPrimaryBtn">Explore Systems <ArrowUpRight size={15}/></a><Link href="/contact" className="btn aluminumSecondaryBtn">Request a Sample</Link></div></div></section>
<section className="aluminumOverview"><div className="wrap aluminumOverviewGrid"><div><span className="aluminumEyebrow dark">ALUMINUM EXTERIOR SYSTEMS</span><h2>Design flexibility.<br/>System coordination.</h2></div><div className="aluminumOverviewCopy"><p>Aluminum siding, soffit and batten systems are often specified where a project requires a crisp exterior expression without compromising resistance to weather, finish wear or maintenance demands.</p><p>In many exterior assemblies, the real decision is not simply “aluminum or not.” It is which profile, drainage strategy, finish and sub-framing approach best suits the façade. CladCan helps match those early decisions to supply, fabrication and installation realities.</p><div className="aluminumMiniBenefits"><span><Check size={14}/> Siding</span><span><Check size={14}/> Soffit</span><span><Check size={14}/> Battens</span><span><Check size={14}/> Woodgrain Finishes</span></div></div></div></section>
<section className="aluminumSystemsSection" id="systems"><div className="wrap"><div className="aluminumSectionHeader"><div><span className="aluminumEyebrow dark">AVAILABLE SYSTEMS</span><h2>Explore aluminum systems.</h2></div><p>Select a system to explore profiles, finishes, applications and project-specific considerations.</p></div><ViewToggleCollection items={subcategories.map(item=>({number:item.number,title:item.title,subtitle:item.subtitle,description:item.description,href:item.href,linkLabel:"Explore System"}))} /></div></section>
<section className="aluminumBenefits"><div className="wrap"><div className="aluminumBenefitsHeader"><span className="aluminumEyebrow">WHY ALUMINUM</span><h2>A versatile exterior material<br/>for demanding applications.</h2></div><div className="aluminumBenefitsGrid">{benefits.map(({icon:Icon,title,text},index)=><article key={title}><span className="aluminumBenefitNumber">{String(index+1).padStart(2,"0")}</span><Icon size={24}/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section className="aluminumApplications"><div className="wrap aluminumApplicationsGrid"><div><span className="aluminumEyebrow dark">APPLICATIONS</span><h2>Designed for walls,<br/>soffits and accents.</h2><p>Aluminum systems commonly appear as primary cladding, soffits, feature panels, battens or privacy elements. They are often coordinated with other materials to create contrast, shadow lines and a stronger architectural rhythm.</p></div><div className="aluminumApplicationsList">{applications.map((application,index)=><div key={application}><span>{String(index+1).padStart(2,"0")}</span><strong>{application}</strong></div>)}</div></div></section>
<section className="aluminumFinishes"><div className="wrap aluminumFinishesInner"><div><span className="aluminumEyebrow dark">COLOURS & FINISHES</span><h2>From clean solid colours<br/>to realistic woodgrain.</h2></div><div><p>Finish options vary by manufacturer and profile. Product-specific availability and warranty conditions should be confirmed before final specification, but aluminum remains a popular choice when a project needs durable, architectural finish flexibility.</p><Link href="/contact" className="aluminumTextLink">Request Colour Samples <ArrowUpRight size={14}/></Link></div></div></section>
<section className="aluminumCTA"><div className="wrap aluminumCTAInner"><div><span className="aluminumEyebrow dark">START A PROJECT</span><h2>Considering aluminum for your exterior?</h2><p>Send us your drawings, elevations or inspiration images. Our team can help review system, profile, finish, fabrication and installation options before the project moves too far ahead.</p></div><Link href="/contact" className="btn aluminumPrimaryBtn">Talk to Our Team <ArrowUpRight size={15}/></Link></div></section>
</main>}