import Link from "next/link";
import { ArrowUpRight, Check, ShieldCheck, Flame, Droplets, Palette } from "lucide-react";
import { aluminumSystems as subcategories } from "@/data/aluminumHierarchy";
import ViewToggleCollection from "@/components/ViewToggleCollection";
export const metadata={title:"Aluminum Siding & Soffit Systems | CladCan",description:"Explore architectural aluminum siding, soffit, battens and woodgrain exterior systems supplied, fabricated and installed by CladCan across Ontario."};

const benefits=[
 {icon:ShieldCheck,title:"Durable",text:"Engineered for long-term exterior exposure with low maintenance requirements."},
 {icon:Flame,title:"Non-Combustible",text:"Aluminum provides an important material option for projects with demanding fire-performance requirements."},
 {icon:Droplets,title:"Weather Resistant",text:"Suitable for exterior wall and soffit applications exposed to Ontario weather conditions."},
 {icon:Palette,title:"Extensive Finish Options",text:"Available in architectural solid colours and realistic woodgrain finishes."},
];
const applications=["Residential façades","Custom homes","Multi-residential buildings","Commercial buildings","Soffits and ceilings","Feature walls","Architectural accents","Privacy screens"];
export default function AluminumPage(){return <main className="aluminumPage">
<section className="aluminumPageHero"><div className="aluminumPageHeroOverlay"/><div className="wrap aluminumPageHeroContent"><span className="aluminumEyebrow">ALUMINUM SIDING & SOFFIT</span><h1>Architectural aluminum<br/><em>built for modern exteriors.</em></h1><p>Durable, non-combustible aluminum wall and soffit systems available in architectural profiles, solid colours and premium woodgrain finishes.</p><div className="aluminumHeroActions"><a href="#systems" className="btn aluminumPrimaryBtn">Explore Aluminum Systems <ArrowUpRight size={15}/></a><Link href="/contact" className="btn aluminumSecondaryBtn">Request a Sample</Link></div></div></section>
<section className="aluminumOverview"><div className="wrap aluminumOverviewGrid"><div><span className="aluminumEyebrow dark">ALUMINUM EXTERIOR SYSTEMS</span><h2>Design flexibility.<br/>Durable performance.</h2></div><div className="aluminumOverviewCopy"><p>Aluminum siding and soffit systems provide architects, builders and homeowners with a durable exterior material capable of delivering both contemporary and wood-inspired aesthetics.</p><p>CladCan works with multiple aluminum systems, profiles and finishes to coordinate material supply, fabrication and installation around the architectural requirements of each project.</p><div className="aluminumMiniBenefits"><span><Check size={14}/> Siding</span><span><Check size={14}/> Soffit</span><span><Check size={14}/> Battens</span><span><Check size={14}/> Woodgrain Finishes</span></div></div></div></section>
<section className="aluminumSystemsSection" id="systems"><div className="wrap"><div className="aluminumSectionHeader"><div><span className="aluminumEyebrow dark">AVAILABLE SYSTEMS</span><h2>Explore aluminum systems.</h2></div><p>Select a system to explore available profiles, finishes, applications and product options.</p></div><ViewToggleCollection items={subcategories.map(item=>({number:item.number,title:item.title,subtitle:item.subtitle,description:item.description,href:item.href,linkLabel:"Explore System"}))} /></div></section>
<section className="aluminumBenefits"><div className="wrap"><div className="aluminumBenefitsHeader"><span className="aluminumEyebrow">WHY ALUMINUM</span><h2>A versatile exterior material<br/>for demanding applications.</h2></div><div className="aluminumBenefitsGrid">{benefits.map(({icon:Icon,title,text},index)=><article key={title}><span className="aluminumBenefitNumber">{String(index+1).padStart(2,"0")}</span><Icon size={24}/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section className="aluminumApplications"><div className="wrap aluminumApplicationsGrid"><div><span className="aluminumEyebrow dark">APPLICATIONS</span><h2>Designed for walls,<br/>soffits and accents.</h2><p>Aluminum systems can be used as primary exterior cladding or coordinated with other façade materials to create transitions, feature areas and architectural contrast.</p></div><div className="aluminumApplicationsList">{applications.map((application,index)=><div key={application}><span>{String(index+1).padStart(2,"0")}</span><strong>{application}</strong></div>)}</div></div></section>
<section className="aluminumFinishes"><div className="wrap aluminumFinishesInner"><div><span className="aluminumEyebrow dark">COLOURS & FINISHES</span><h2>From clean solid colours<br/>to realistic woodgrain.</h2></div><div><p>Aluminum exterior systems are available in a broad range of factory-applied architectural finishes. Product-specific colour availability varies by manufacturer and profile.</p><Link href="/contact" className="aluminumTextLink">Request Colour Samples <ArrowUpRight size={14}/></Link></div></div></section>
<section className="aluminumCTA"><div className="wrap aluminumCTAInner"><div><span className="aluminumEyebrow dark">START A PROJECT</span><h2>Considering aluminum for your exterior?</h2><p>Send us your drawings, elevations or inspiration images. Our team can help review system, profile, finish, fabrication and installation options.</p></div><Link href="/contact" className="btn aluminumPrimaryBtn">Talk to Our Team <ArrowUpRight size={15}/></Link></div></section>
</main>}
