import CurrentSitePage from "@/components/CurrentSitePage";
export const metadata={title:'IMP (Insulated Metal Panel)'+" | CladCan",description:'Insulated Metal Panels combine exterior metal skins and insulation in a single efficient building-envelope component, supporting thermal performance, air and moisture control, and fast installation.'};
const supportingNotes = [
  {label:"What it is", text:"Insulated Metal Panels are prefabricated wall systems that combine metal skins and insulation in a single panelized assembly, helping create a disciplined building-envelope layer with efficient thermal performance."},
  {label:"Where it fits", text:"They are often used in commercial, institutional and industrial applications where clean lines, efficient envelope construction and repeatable panel geometry are part of the brief."},
  {label:"Selection factors", text:"Panel joint design, flashing, opening coordination, attachment method and installation sequence all matter when integrating IMPs into an enclosure strategy."},
  {label:"How CladCan helps", text:"CladCan can support product comparison, panel coordination and field execution planning around a project’s broader wall and roof integration requirements."}
];
export default function Page(){return <CurrentSitePage title={'IMP (Insulated Metal Panel)'} intro={'Insulated Metal Panels combine exterior metal skins and insulation in a single efficient building-envelope component, supporting thermal performance, air and moisture control, and fast installation.'} overview={'IMP systems are often evaluated for commercial and industrial façades where a strong envelope performance profile and efficient panelized assembly are important. The actual fit depends on joint detailing, openings, substrate conditions and installation coordination.'} items={[{title:'Commercial & Industrial Walls',href:'/exterior-systems/imp/commercial-industrial-walls',text:'Efficient envelope solutions for commercial, industrial and institutional buildings.'},{title:'Thermal Performance',href:'/exterior-systems/imp/thermal-performance',text:'Integrated insulation helps simplify high-performance wall assemblies.'},{title:'Clean Architectural Finish',href:'/exterior-systems/imp/architectural-finish',text:'Metal faces provide a durable, modern exterior appearance.'},{title:'Coordinated Installation',href:'/exterior-systems/imp/coordinated-installation',text:'Panel joints, openings and transitions are coordinated as part of the overall envelope.'}]} decisionSupport={supportingNotes} />;}
