import CurrentSitePage from "@/components/CurrentSitePage";
export const metadata={title:'Natural Wood'+" | CladCan",description:'Natural wood siding and soffit bring timeless warmth, authentic texture, and organic character to residential and commercial exteriors.'};
const supportingNotes = [
  {label:"What it is", text:"Natural wood cladding brings a warm, tactile material language that is often used where the exterior needs a stronger organic or traditional character."},
  {label:"Where it fits", text:"Wood is commonly selected for residential façades, feature walls, soffits, accents and mixed-material facades where material contrast is part of the design story."},
  {label:"Selection factors", text:"Species, profile, finish treatment, exposure, maintenance expectations and detailing around openings all influence how the material will age and perform in the field."},
  {label:"How CladCan helps", text:"CladCan can help coordinate species and profile direction, accessory planning and installation sequencing around the actual project conditions."}
];
export default function Page(){return <CurrentSitePage title={'Natural Wood'} intro={'Natural wood siding and soffit bring timeless warmth, authentic texture, and organic character to residential and commercial exteriors.'} overview={'Natural wood finishes are often chosen when a project needs warmth, depth and material authenticity, but this category requires careful coordination around detailing, finish, maintenance and exposure.'} items={[{title:'Natural Wood Siding',href:'/exterior-systems/natural-wood/siding',text:'Premium wood exterior applications for modern and traditional architecture.'},{title:'Natural Wood Soffit',href:'/exterior-systems/natural-wood/soffit',text:'Warm natural material expression for protected soffit and ceiling applications.'},{title:'Architectural Accents',href:'/exterior-systems/natural-wood/architectural-accents',text:'Wood can be coordinated with metal, fibre cement and other façade materials for contrast and depth.'}]} decisionSupport={supportingNotes} />;}
