import CurrentSitePage from "@/components/CurrentSitePage";
export const metadata={title:'PVC'+" | CladCan",description:'uPVC vinyl siding combines cost-effectiveness, durability and low maintenance with a range of profiles for exterior and architectural applications.'};
const supportingNotes = [
  {label:"What it is", text:"PVC systems are often selected where a project needs a lower-maintenance, profile-based exterior cladding option with a wide range of finish and panel styles."},
  {label:"Where it fits", text:"They are commonly used in residential and light commercial work where a cost-conscious system, practical upkeep and visible profile variation are important considerations."},
  {label:"Selection factors", text:"Thermal movement, fastening strategy, panel expansion and the detailing around openings, corners and trim all shape how successfully a PVC system performs over time."},
  {label:"How CladCan helps", text:"CladCan can compare product families, coordinate corresponding trims and accessories, and support installation sequencing around the project’s conditions."}
];
export default function Page(){return <CurrentSitePage title={'PVC'} intro={'PVC systems can be a practical choice for residential and light commercial exteriors where a broad range of profile styles, finish options and lower-maintenance expectations are part of the design brief.'} overview={'PVC siding and soffit products are commonly evaluated alongside other exterior systems for cost, finish range, weather resistance and ease of upkeep. Product selection should consider profile design, substrate compatibility, thermal movement, fastening, and the manufacturer’s installation requirements.'} items={[{title:'uPVC Vinyl Cladding',href:'/exterior-systems/pvc/vinyl-cladding',text:'Profile-based cladding designed for residential and light commercial exterior applications.'},{title:'Wall Cladding Panels',href:'/exterior-systems/pvc/wall-cladding-panels',text:'Panelized options that can support contemporary wall and feature-area expressions.'},{title:'Soffit Panels',href:'/exterior-systems/pvc/soffit-panels',text:'Low-maintenance soffit solutions suited to practical roofline detailing.'},{title:'Profiles & Finishes',href:'/exterior-systems/pvc/profiles-finishes',text:'Alternative profile and finish options that influence visual expression and project coordination.'}]} decisionSupport={supportingNotes} />;}
