import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, Clock3 } from "lucide-react";

export const metadata={title:"CladCan Insights | Exterior Materials, Design & Building Envelope",description:"Practical CladCan insights on exterior materials, façade design, maintenance, project planning and building-envelope decisions."};
const posts=[
 {cat:"Materials",date:"Jan 15, 2024",read:"8 min",title:"The Complete Guide to Choosing Exterior Cladding Materials",desc:"A practical framework for comparing exterior systems by performance, aesthetics, budget and long-term maintenance.",href:"/blog/guide-to-cladding-materials",tone:"insightTone1",tag:"START HERE"},
 {cat:"Maintenance",date:"Mar 18, 2026",read:"Guide",title:"ACM Panel Maintenance Playbook: Keep Facades Looking New",desc:"A maintenance-oriented article outlining inspection, cleaning and repair considerations for ACM façades.",href:"/blog/acm-panel-maintenance-playbook",tone:"insightTone2"},
 {cat:"Planning",date:"Mar 2, 2026",read:"Checklist",title:"Façade Budget Planning Checklist for 2026 Projects",desc:"Budget conversations are stronger when material, fabrication, access and installation assumptions are surfaced early.",href:"/blog/facade-budget-planning-checklist",tone:"insightTone3"},
];
const topics=["Materials","Design","Technical","Maintenance","Project Planning","Field Notes"];
export default function Blog(){return <>
 <section className="projectsV11Hero"><div className="wrap"><div className="projectsV11HeroGrid"><div><span className="eyebrow">CLADCAN INSIGHTS</span><h1>Better exterior decisions<br/>start before installation.</h1></div><div><p>Material comparisons, technical context, maintenance guidance and project-planning notes for people making decisions about the building exterior.</p><Link href="#insights-library">Explore insights <ArrowDownRight size={18}/></Link></div></div></div></section>

 <section className="insightsFeature"><div className="wrap"><Link href="/blog/guide-to-cladding-materials" className="insightsFeatureCard"><div className="insightsFeatureVisual"><span>01</span><div><small>FEATURED / MATERIALS</small><b>Cladding is a performance decision before it is a finish decision.</b></div></div><div className="insightsFeatureCopy"><div className="insightsMeta"><span>JAN 15, 2024</span><span><Clock3 size={11}/> 8 MIN READ</span></div><h2>The Complete Guide to Choosing Exterior Cladding Materials</h2><p>Start with moisture, thermal, fire, weather and lifecycle requirements—then compare the material systems that can meet the architectural intent.</p><strong>Read the guide <ArrowUpRight size={13}/></strong></div></Link></div></section>

 <section className="insightsTopics"><div className="wrap"><span>EXPLORE BY QUESTION</span><div className="insightsTopicRail">{topics.map((x,i)=><div key={x}><small>{String(i+1).padStart(2,"0")}</small><b>{x}</b></div>)}</div></div></section>

 <section id="insights-library" className="insightsLibrary"><div className="wrap"><div className="insightsLibraryHead"><div><span>THE LIBRARY</span><h2>Useful, specific,<br/>connected to the work.</h2></div><p>Insights should help a reader make a decision—and then make it easy to continue into the relevant exterior system, service or project.</p></div><div className="insightsGrid">{posts.map((p,i)=>{const body=<><div className={`insightsCardVisual ${p.tone}`}><span>{String(i+1).padStart(2,"0")}</span>{p.tag&&<b>{p.tag}</b>}</div><div className="insightsCardBody"><div className="insightsMeta"><span>{p.cat}</span><span>{p.read}</span></div><h3>{p.title}</h3><p>{p.desc}</p><strong>{p.href?"Read article":"Editorial slot"} <ArrowUpRight size={12}/></strong></div></>;return p.href?<Link href={p.href} className="insightsCard" key={p.title}>{body}</Link>:<article className="insightsCard" key={p.title}>{body}</article>})}</div></div></section>

 <section className="insightsFunnel"><div className="wrap insightsFunnelGrid"><div><span>FROM RESEARCH TO PROJECT</span><h2>Found the material.<br/>Now explore the system.</h2></div><div><p>The editorial library is intentionally connected to the commercial site architecture rather than living as a separate archive.</p><div className="insightsFunnelLinks"><Link href="/exterior-systems">Exterior Systems <ArrowUpRight size={13}/></Link><Link href="/projects">Project Library <ArrowUpRight size={13}/></Link><Link href="/contact">Ask CladCan <ArrowUpRight size={13}/></Link></div></div></div></section>
</>}
