import Link from "next/link";
import { ArrowUpRight, Boxes, DraftingCompass, Factory, Hammer, Layers3, ShieldCheck } from "lucide-react";

export const metadata={title:"About CladCan | Integrated Exterior Delivery",description:"CladCan connects exterior material supply, fabrication, installation and design support for residential, commercial and institutional projects across Ontario."};

const capabilities=[
  ["01","Specify","System thinking before procurement","Material, profile, finish and constructability decisions are clarified around the actual project—not a generic catalogue.",DraftingCompass,"/exterior-systems"],
  ["02","Source","A broader exterior material ecosystem","Coordinate cladding, soffit and related exterior components across multiple material families and established manufacturers.",Boxes,"/services/material-supply"],
  ["03","Make","Fabrication where details matter","Custom panels, trims, flashings, Z-bars, hat channels and project-specific transitions help turn drawings into buildable assemblies.",Factory,"/services/custom-fabrication"],
  ["04","Install","Field execution connected to the details","Installation is coordinated with dimensions, substrate conditions, transitions and visible finish quality.",Hammer,"/services/installation"],
];
const process=["Project brief","Site / drawing review","System & sample alignment","Shop drawings / detailing","Procurement & fabrication","Installation","Quality review","Post-handover support"];

export default function Page(){return <>
  <section className="aboutV8Hero"><div className="aboutV8HeroVisual"/><div className="wrap aboutV8HeroInner"><div className="aboutV8Kicker">CLADCAN / BUILDING ENVELOPE & FAÇADE</div><h1>Exterior delivery,<br/><em>connected.</em></h1><div className="aboutV8HeroFoot"><p>CladCan brings material supply, fabrication, installation and design support into one coordinated exterior workflow—reducing handoffs between the decisions made on paper and the work delivered on site.</p><div><Link href="/projects">See the work <ArrowUpRight size={14}/></Link><Link href="/contact">Start a project <ArrowUpRight size={14}/></Link></div></div></div></section>

  <section className="aboutV8Manifesto"><div className="wrap aboutV8ManifestoGrid"><div><span className="eyebrow">THE OPERATING IDEA</span><h2>A façade is not a collection of isolated products.</h2></div><div><p className="lead">It is a sequence of decisions—material, geometry, transitions, fabrication, procurement and field execution.</p><p>CladCan’s role is to connect those decisions. The team supports exterior projects from early material conversations through fabrication and installation, helping project teams align finish intent, system selection and delivery requirements without losing sight of buildability.</p><div className="aboutV8MiniProof"><span><Layers3/> Multi-system exterior portfolio</span><span><ShieldCheck/> Coordination through delivery</span></div></div></div></section>

  <section className="aboutV8Capabilities"><div className="wrap"><div className="aboutV8SectionHead"><span>01 / THE MODEL</span><h2>Four capabilities.<br/>One exterior workflow.</h2><p>The distinction is not simply offering more services. It is keeping information moving between them.</p></div><div className="aboutV8CapabilityRail">{capabilities.map(([n,verb,title,text,Icon,href])=><Link href={href} key={verb}><div className="aboutV8CapTop"><span>{n}</span><Icon size={20}/></div><b>{verb}</b><h3>{title}</h3><p>{text}</p><strong>Explore <ArrowUpRight size={12}/></strong></Link>)}</div></div></section>

  <section className="aboutV8Markets"><div className="wrap aboutV8MarketsGrid"><div className="aboutV8MarketsVisual"><div><span>PROJECT CONTEXT</span><strong>From façade concept<br/>to field condition.</strong></div></div><div className="aboutV8MarketsCopy"><span className="eyebrow">02 / WHERE WE FIT</span><h2>Built for teams making real project decisions.</h2><p>Homeowners may need a clear path through materials and installation. Architects and designers need profile, finish and detailing support. Builders and general contractors need scope clarity, coordination and reliable execution.</p><div className="aboutV8Audience"><div><span>01</span><b>Residential</b><small>Renovations · custom homes · additions</small></div><div><span>02</span><b>Commercial</b><small>Retail · offices · mixed-use façades</small></div><div><span>03</span><b>Institutional</b><small>Exterior upgrades · coordinated envelope scopes</small></div></div></div></div></section>

  <section className="aboutV8Process"><div className="wrap"><div className="aboutV8SectionHead inverse"><span>03 / DELIVERY</span><h2>The project moves.<br/>The information should too.</h2><p>A practical sequence from first inquiry through closeout.</p></div><div className="aboutV8ProcessGrid">{process.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b></div>)}</div></div></section>

  <section className="aboutV8Proof"><div className="wrap aboutV8ProofGrid"><div><span className="eyebrow">04 / PROOF, NOT PROMISES</span><h2>Judge the company by the work.</h2><p>Explore completed exterior transformations, material combinations and façade details. As the new site is populated, this section is designed to prioritize verified project photography and case-study evidence over generic claims.</p><Link href="/projects" className="aboutV8TextLink">Explore Projects <ArrowUpRight size={14}/></Link></div><div className="aboutV8ProofCards"><Link href="/projects"><span>PROJECT LIBRARY</span><strong>Residential + commercial work</strong><ArrowUpRight/></Link><Link href="/exterior-systems"><span>SYSTEM LIBRARY</span><strong>Compare exterior systems</strong><ArrowUpRight/></Link></div></div></section>

  <section className="aboutV8Final"><div className="wrap"><span>HAVE A PROJECT IN MIND?</span><h2>Bring us the drawings.<br/>Or just bring the question.</h2><p>Early concepts, tender packages, renovation photos and material-selection questions are all valid starting points.</p><Link href="/contact" className="btn internalRedBtn">Start a Project <ArrowUpRight size={15}/></Link></div></section>
</>}
