import Link from "next/link";
import ProjectsCatalogue from "@/components/ProjectsCatalogue";
import { ArrowDownRight } from "lucide-react";
export const metadata={title:"Exterior Cladding Projects | CladCan",description:"Explore selected CladCan exterior cladding and façade projects across Toronto and the GTA, including ACM, aluminum, cedar, soffit and multi-material exterior systems."};
const projects=[
 {title:"Sideroad 17 Exterior Transformation",location:"Schomberg, ON",type:"Residential",tags:["Residential","Before & After"],systems:["Exterior Cladding"],image:"/images/before-after/sideroad-17-schomberg-after.jpg",href:"/projects/sideroad-17-schomberg",summary:"A residential exterior transformation documented with verified before-and-after photography."},
 {title:"Gray Lane Exterior Transformation",location:"Barrie, ON",type:"Residential",tags:["Residential","Before & After"],systems:["Exterior Cladding"],image:"/images/before-after/gray-lane-barrie-after.jpg",href:"/projects/gray-lane-barrie",summary:"A before-and-after façade transformation in Barrie showing the visual impact of a coordinated exterior renewal."},
 {title:"Pharmacy Avenue Exterior Transformation",location:"Scarborough, ON",type:"Commercial",tags:["Commercial","Before & After"],systems:["Exterior Cladding"],image:"/images/before-after/pharmacy-scarborough-after.jpg",href:"/projects/pharmacy-scarborough",summary:"Commercial exterior work in Scarborough documented through existing-condition and completed-project photography."},
 {title:"ACM + Cedar Soffit & Fascia",location:"Toronto, ON",type:"Multi-material",tags:["Multi-material"],systems:["ACM Panel","Cedar Siding","Fascia","Soffit"],href:"/projects/acm-cedar-soffit-fascia",summary:"ACM panel installation complemented by cedar soffit and fascia detailing for a refined multi-material exterior."},
 {title:"ACM + Stucco Façade",location:"Toronto, ON",type:"Multi-material",tags:["Commercial","Multi-material"],systems:["ACM Panel","Stucco"],href:"/projects/acm-stucco-toronto",summary:"A Toronto façade combining ACM panels and stucco to create contrast, depth and a clean contemporary expression."},
 {title:"Luxclad ACM Façade",location:"Richmond Hill, ON",type:"Commercial",tags:["Commercial"],systems:["ACM Panel","Luxclad"],href:"/projects/luxclad-richmond-hill",summary:"ACM installation using the Luxclad system with concealed-fastener detailing for a contemporary commercial façade."}
];
export default function Projects(){return <>
 <section className="projectsV11Hero"><div className="wrap"><div className="projectsV11Crumb"><Link href="/">Home</Link><span>/</span><span>Projects</span></div><div className="projectsV11HeroGrid"><div><span className="eyebrow">SELECTED WORK · ONTARIO</span><h1>Built work.<br/><em>Real context.</em></h1></div><div><p>Explore exterior transformations, façade systems and multi-material projects delivered across Toronto and the GTA. Each case study is designed to show the system, scope and execution—not just the finished image.</p><a href="#project-index">Explore projects <ArrowDownRight size={18}/></a></div></div></div></section>
 <section className="projectsV11Statement"><div className="wrap"><span>01</span><h2>A project library that connects <em>materials, services and execution.</em></h2><p>Filter by project context, then open a case study to see verified project information, photography and related exterior systems.</p></div></section>
 <div id="project-index"><ProjectsCatalogue projects={projects}/></div>
 <section className="projectsV11CTA"><div className="wrap"><span className="eyebrow">START A PROJECT</span><h2>Have drawings, photos<br/>or a tender package?</h2><p>Send the project information you already have. We can review the scope and identify the right next step.</p><Link href="/contact">Start a project <span>↗</span></Link></div></section>
 </>}
