"use client";
import { useEffect } from "react";
const ENDPOINT="https://formsubmit.co/info@cladcan.ca",STORAGE_KEY="cladcan_chat_leads",FRAME_NAME="cladcan-chat-formsubmit-frame";
function label(k){return String(k||"").replace(/_/g," ").replace(/\b\w/g,m=>m.toUpperCase())}
function hidden(form,name,value){const i=document.createElement("input");i.type="hidden";i.name=name;i.value=String(value??"");form.appendChild(i)}
function flatten(form,value,prefix=""){if(value==null)return;if(typeof value==="object"&&!Array.isArray(value)){Object.entries(value).forEach(([k,v])=>flatten(form,v,prefix?`${prefix} — ${label(k)}`:label(k)));return}hidden(form,prefix||"Details",Array.isArray(value)?value.join(", "):value)}
export default function ChatLeadFormSubmitBridge(){useEffect(()=>{let frame=document.querySelector(`iframe[name="${FRAME_NAME}"]`);if(!frame){frame=document.createElement("iframe");frame.name=FRAME_NAME;frame.title="Chat inquiry submission";frame.style.display="none";document.body.appendChild(frame)}
let captured=[];const onFile=e=>{const input=e.target;if(!(input instanceof HTMLInputElement)||input.type!=="file"||!input.closest(".chatPanel"))return;captured=Array.from(input.files||[]).filter(f=>f instanceof File)};document.addEventListener("change",onFile,true);
const original=window.localStorage.setItem.bind(window.localStorage);window.localStorage.setItem=function(key,value){original(key,value);if(key!==STORAGE_KEY)return;try{const leads=JSON.parse(value||"[]"),lead=Array.isArray(leads)?leads.at(-1):null;if(!lead)return;const form=document.createElement("form");form.action=ENDPOINT;form.method="POST";form.enctype="multipart/form-data";form.target=FRAME_NAME;form.style.display="none";const flow=label(lead.flow||"Chatbot inquiry");hidden(form,"_subject",`CladCan chatbot inquiry — ${flow}`);hidden(form,"_template","table");hidden(form,"_captcha","false");hidden(form,"_url","https://cladcan.ca");hidden(form,"Source","CladCan Project Assistant");hidden(form,"Inquiry Type",flow);hidden(form,"Priority",lead.priority?"Urgent":"Standard");hidden(form,"Submitted At",lead.createdAt||new Date().toISOString());flatten(form,lead.values||{});
if(captured.length){const dt=new DataTransfer();captured.forEach(f=>dt.items.add(f));const fileInput=document.createElement("input");fileInput.type="file";fileInput.name="attachment";fileInput.multiple=true;fileInput.files=dt.files;form.appendChild(fileInput);hidden(form,"Attached files",captured.map(f=>`${f.name} (${Math.ceil(f.size/1024)} KB)`).join(", "))}document.body.appendChild(form);form.submit();setTimeout(()=>form.remove(),15000);captured=[]}catch(err){console.error("Chatbot FormSubmit bridge error:",err)}};return()=>{document.removeEventListener("change",onFile,true);window.localStorage.setItem=original}},[]);return null}
