"use client";
import { useEffect, useRef, useState } from "react";
import { MessageCircle, X, AlertTriangle, ArrowLeft, Upload, MapPin, Phone, Mail, Clock3, CheckCircle2 } from "lucide-react";

const MAIN_MENU=[{label:"Urgent Issue / Leak",flow:"urgent",priority:true},{label:"Request a Quote",flow:"quote",primary:true},{label:"Discuss a Project",flow:"project"},{label:"Products & Materials",flow:"products"},{label:"Services We Offer",flow:"services"},{label:"Technical / General Questions",flow:"technical"},{label:"Careers",flow:"careers"},{label:"Contact Information",flow:"contact"},{label:"Book a Showroom Visit",flow:"showroom"}];
const SERVICES=["Installation","Material Supply","Fabrication","Design Assistance","Full Design-Build","Repairs","Not sure"];
const MATERIALS=["ACM Panels","Aluminum Cladding","Fiber Cement","WPC / Composite Siding","Natural Wood","Stucco / EIFS","Roofing","Windows / Doors","Railings","Other / Not sure"];
const PRODUCT_CATEGORIES=["ACM Panels","Aluminum Panels","Fiber Cement","WPC / Composite Siding","Natural Wood","Stucco / EIFS","Roofing Materials","Windows / Doors","Railings","Other"];
const TECH_QA=[{q:"Areas served",a:"CladCan serves projects across Ontario and other regions depending on project scope and requirements. Please contact us with your project location for confirmation."},{q:"Do you work with general contractors and developers?",a:"Yes. CladCan works with general contractors, developers, consultants, and property owners on a range of exterior cladding projects."},{q:"Do you provide repair work?",a:"Yes. CladCan provides repair-related services for exterior systems, depending on project scope and site conditions."},{q:"Do you offer material supply only?",a:"Yes. CladCan can assist with material supply inquiries depending on the product category and project requirements."},{q:"Can I send drawings or tender documents?",a:"Yes. You can submit drawings, specifications, and project documents through the quote request process or by contacting the team directly."}];
const FLOW_CONFIG={
urgent:{intro:"We understand this may be time-sensitive. Please provide a few details so we can direct your request as quickly as possible.",final:"Thank you. Your request has been submitted. A member of the CladCan team will review the issue and contact you as soon as possible.",priority:true,steps:[{key:"active_now",type:"choice",prompt:"Is the issue active right now?",options:["Yes, active leak","No, inspection needed","Not sure"]},{key:"issue_location",type:"choice",prompt:"Where is the issue located?",options:["Roof","Wall / Cladding","Window / Door","Balcony / Railing","Interior ceiling / wall","Not sure"]},{key:"property_type",type:"choice",prompt:"What type of property is this?",options:["Commercial","Residential","Condo / Multi-unit","Institutional","Other"]},{key:"property_location",type:"text",prompt:"Where is the property located?",placeholder:"City / address"},{key:"issue_description",type:"textarea",prompt:"Please briefly describe the issue.",placeholder:"Describe the leak, damage, or inspection concern"},{key:"photos",type:"fileChoice",prompt:"Would you like to upload photos?",options:["Yes","No"],accept:"image/*"},{key:"contact",type:"contact",prompt:"Please provide your contact information.",companyOptional:true}]},
quote:{intro:"Let’s get the project basics first. We’ll keep this short, then you can add more detail if useful.",final:"Thank you. Your project inquiry has been submitted. A member of the CladCan team will review the information and contact you within 24 to 48 hours.",steps:[{key:"project_type",type:"choice",prompt:"What type of project is this?",options:["Commercial","Residential","Institutional","Mixed-Use","Other"]},{key:"project_location",type:"text",prompt:"Where is the project located?",placeholder:"City / address"},{key:"service",type:"choice",prompt:"What service are you looking for?",options:SERVICES},{key:"contact",type:"contact",prompt:"Please provide your contact details."},{key:"more_detail",type:"choice",prompt:"Would you like to provide additional project details to help us review your request faster?",options:["Yes","Skip for now"]},{key:"material",type:"choice",prompt:"Which system or material are you interested in?",options:MATERIALS,optionalAfter:"more_detail"},{key:"stage",type:"choice",prompt:"What stage is the project currently in?",options:["Planning","Tender","Construction","Repair / Existing Building","Other"],optionalAfter:"more_detail"},{key:"size",type:"choice",prompt:"What is the estimated project size?",options:["Under 1,000 sqft","1,000 to 2,000 sqft","2,000 to 10,000 sqft","Over 10,000 sqft","Not sure"],optionalAfter:"more_detail"},{key:"scope",type:"textarea",prompt:"Please provide a brief description of the scope of work.",placeholder:"Brief project scope",optionalAfter:"more_detail"},{key:"files",type:"fileChoice",prompt:"Would you like to upload drawings, specifications, or photos?",options:["Yes","No"],accept:".pdf,.dwg,.dxf,.doc,.docx,.jpg,.jpeg,.png,.webp",optionalAfter:"more_detail"}]},
project:{intro:"We can help with early-stage project discussion before a formal quote.",final:"Thank you. Your request has been sent to our team. We will contact you to discuss the project further.",steps:[{key:"help_type",type:"choice",prompt:"What would you like help with?",options:["Choosing materials","Reviewing project feasibility","Discussing drawings or plans","Understanding scope options","General project consultation"]},{key:"project_type",type:"choice",prompt:"What type of project is it?",options:["Commercial","Residential","Institutional","Mixed-Use","Other"]},{key:"project_location",type:"text",prompt:"Where is the project located?",placeholder:"City / address"},{key:"request_description",type:"textarea",prompt:"Please briefly describe what you are looking for.",placeholder:"What would you like to discuss?"},{key:"files",type:"fileChoice",prompt:"Would you like to upload drawings, photos, or specifications?",options:["Yes","No"],accept:".pdf,.dwg,.dxf,.doc,.docx,.jpg,.jpeg,.png,.webp"},{key:"contact",type:"contact",prompt:"Please provide your contact details."}]},
products:{intro:"Select a product or material category and we’ll route the inquiry toward pricing, availability, or project discussion.",final:"Thank you. Your inquiry has been sent to our team. We will contact you shortly with more information.",steps:[{key:"product",type:"choice",prompt:"Please select the product or material category you are interested in.",options:PRODUCT_CATEGORIES},{key:"product_help",type:"choice",prompt:"How can we assist you with this product?",options:["Request pricing","Check availability","Discuss a project","Material supply inquiry","Back to main menu"]},{key:"project_location",type:"text",prompt:"Where is the project located?",placeholder:"City / address"},{key:"quantity",type:"text",prompt:"What is the approximate quantity or project size?",placeholder:"Approximate quantity / sqft"},{key:"files",type:"fileChoice",prompt:"Do you have drawings, specifications, or product requirements to share?",options:["Yes","No"],accept:".pdf,.dwg,.dxf,.doc,.docx,.jpg,.jpeg,.png,.webp"},{key:"contact",type:"contact",prompt:"Please provide your contact details."}]},
careers:{intro:"Please provide the details below and attach your resume.",final:"Thank you. Your application has been submitted.",steps:[{key:"applicant",type:"applicant",prompt:"Applicant details"},{key:"position",type:"text",prompt:"Position applying for",placeholder:"Position / role"},{key:"resume",type:"file",prompt:"Upload your resume",accept:".pdf,.doc,.docx"},{key:"message",type:"textarea",prompt:"Message",placeholder:"Optional message to our hiring team"}]},
contact:{intro:"Here are CladCan’s direct contact details. You can also send a message now.",final:"Thank you. Your message has been sent to our team.",steps:[{key:"contact_info",type:"info",prompt:"Contact Information"},{key:"send_message",type:"choice",prompt:"Would you like to send us a message now?",options:["Yes","Main Menu"]},{key:"message_form",type:"messageContact",prompt:"Message form"}]},
showroom:{intro:"Please provide your preferred visit details. A member of our team will contact you to confirm availability.",final:"Thank you. Your showroom visit request has been submitted. A member of our team will contact you to confirm availability.",steps:[{key:"visitor",type:"contact",prompt:"Visitor details"},{key:"preferred_date",type:"date",prompt:"Preferred date"},{key:"preferred_time",type:"time",prompt:"Preferred time"},{key:"interest",type:"text",prompt:"Area of interest / products to review",placeholder:"Products or systems you want to see"},{key:"message",type:"textarea",prompt:"Additional message",placeholder:"Optional message"}]}}
function saveLeadLocally(payload){try{const existing=JSON.parse(localStorage.getItem("cladcan_chat_leads")||"[]");existing.push({...payload,createdAt:new Date().toISOString()});localStorage.setItem("cladcan_chat_leads",JSON.stringify(existing));}catch(e){}}
function validEmail(v){const s=String(v||"").trim();return s.length<=254&&/^[A-Za-z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$/.test(s)&&!s.includes("..");}
function validPhone(v){let d=String(v||"").replace(/\D/g,"");if(d.length===11&&d[0]==="1")d=d.slice(1);return /^[2-9]\d{2}[2-9]\d{6}$/.test(d)&&!(/^(\d)\1{9}$/.test(d))&&!(["1234567890","0123456789","9876543210"].includes(d));}
function validateContactForm(form){const email=form.elements.email,phone=form.elements.phone;email?.setCustomValidity("");phone?.setCustomValidity("");if(!form.checkValidity()){form.reportValidity();return false;}if(email&&!validEmail(email.value)){email.setCustomValidity("Please enter a valid email address, for example name@example.com.");email.reportValidity();email.focus();return false;}if(phone&&!validPhone(phone.value)){phone.setCustomValidity("Please enter a valid 10-digit Canadian or US phone number, for example (416) 555-1234.");phone.reportValidity();phone.focus();return false;}return true;}
export default function ChatWidget(){const[open,setOpen]=useState(false),[screen,setScreen]=useState("menu"),[flowName,setFlowName]=useState(null),[stepIndex,setStepIndex]=useState(0),[values,setValues]=useState({}),[draft,setDraft]=useState(""),[files,setFiles]=useState({}),[notice,setNotice]=useState(""),[inactivePrompt,setInactivePrompt]=useState(false);const timerRef=useRef(null);const flow=flowName?FLOW_CONFIG[flowName]:null,step=flow?.steps?.[stepIndex];
function resetIdle(){clearTimeout(timerRef.current);if(open)timerRef.current=setTimeout(()=>setInactivePrompt(true),90000)}useEffect(()=>{resetIdle();return()=>clearTimeout(timerRef.current)},[open,screen,stepIndex]);
function mainMenu(){setScreen("menu");setFlowName(null);setStepIndex(0);setValues({});setDraft("");setFiles({});setNotice("");setInactivePrompt(false)}function startFlow(name){if(name==="services"){setScreen("services");return}if(name==="technical"){setScreen("technical");return}setFlowName(name);setStepIndex(0);setValues({});setDraft("");setFiles({});setNotice("");setScreen("flow")}
function advance(extra={}){const updated={...values,...extra};setValues(updated);setDraft("");setNotice("");let next=stepIndex+1;while(flow?.steps?.[next]?.optionalAfter&&updated[flow.steps[next].optionalAfter]==="Skip for now")next++;if(next>=(flow?.steps?.length||0)){const fileSummary=Object.fromEntries(Object.entries(files).map(([k,arr])=>[k,(arr||[]).map(f=>f.name)]));saveLeadLocally({flow:flowName,priority:!!flow?.priority,values:updated,files:fileSummary});setScreen("done");return}setStepIndex(next)}
function back(){if(screen!=="flow"||stepIndex===0){mainMenu();return}setStepIndex(stepIndex-1)}function selectChoice(choice){if(choice==="Back to main menu"||choice==="Main Menu"){mainMenu();return}setValues(v=>({...v,[step.key]:choice}));if(step.type==="fileChoice"&&choice==="Yes"){setNotice("No file selected yet.");return}advance({[step.key]:choice})}function submitDraft(){if(draft.trim())advance({[step.key]:draft.trim()})}
function collectContact(form){if(!validateContactForm(form))return;advance({[step.key]:Object.fromEntries(new FormData(form).entries())})}
function handleFiles(e){const selected=Array.from(e.target.files||[]);setFiles(f=>({...f,[step.key]:selected}));setNotice(selected.length?`${selected.length} file${selected.length===1?"":"s"} attached: ${selected.map(f=>f.name).join(", ")}`:"No file selected.")}
function contactFields(message=false){return <><input required name="full_name" placeholder="Full name"/><input name="company_name" placeholder="Company name (optional)"/><input required type="email" name="email" placeholder="Email" onInput={e=>e.currentTarget.setCustomValidity("")}/><input required type="tel" inputMode="tel" name="phone" placeholder="Phone number" onInput={e=>e.currentTarget.setCustomValidity("")}/>{message&&<textarea required name="message" rows="4" placeholder="Message"/>}</>}
function renderStep(){if(!step)return null;if(step.type==="choice"||step.type==="fileChoice")return <><div className="chatPrompt">{step.prompt}</div><div className="chatOptions">{step.options.map(o=><button key={o} onClick={()=>selectChoice(o)}>{o}</button>)}</div>{step.type==="fileChoice"&&values[step.key]==="Yes"&&<><label className={`chatFileUpload ${files[step.key]?.length?"hasFile":""}`}><Upload size={17}/><span>{notice||"Choose files"}</span><input type="file" multiple accept={step.accept} onChange={handleFiles}/></label>{files[step.key]?.length>0&&<div className="chatAttachmentConfirmed"><CheckCircle2 size={16}/> Attached successfully</div>}<button className="chatActionBtn" onClick={()=>files[step.key]?.length?advance({[step.key]:"Yes"}):setNotice("Please choose at least one file, or select No.")}>Continue</button></>} </>;
if(step.type==="text"||step.type==="textarea")return <><div className="chatPrompt">{step.prompt}</div>{step.type==="textarea"?<textarea className="chatField" rows="4" placeholder={step.placeholder||""} value={draft} onChange={e=>setDraft(e.target.value)}/>:<input className="chatField" placeholder={step.placeholder||""} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submitDraft()}/>}<button className="chatActionBtn" onClick={submitDraft}>Continue</button></>;
if(step.type==="date"||step.type==="time")return <><div className="chatPrompt">{step.prompt}</div><input className="chatField" type={step.type} value={draft} onChange={e=>setDraft(e.target.value)}/><button className="chatActionBtn" onClick={submitDraft}>Continue</button></>;
if(step.type==="file")return <><div className="chatPrompt">{step.prompt}</div><label className={`chatFileUpload ${files[step.key]?.length?"hasFile":""}`}><Upload size={17}/><span>{notice||"Choose file"}</span><input type="file" accept={step.accept} onChange={handleFiles}/></label>{files[step.key]?.length>0&&<div className="chatAttachmentConfirmed"><CheckCircle2 size={16}/> {files[step.key][0].name} attached</div>}<button className="chatActionBtn" onClick={()=>files[step.key]?.length?advance({[step.key]:"uploaded"}):setNotice("Please choose a file before continuing.")}>Continue</button></>;
if(["contact","applicant","messageContact"].includes(step.type))return <form className="chatMiniForm" onSubmit={e=>{e.preventDefault();collectContact(e.currentTarget)}}><div className="chatPrompt">{step.prompt}</div>{contactFields(step.type==="messageContact")}<button className="chatActionBtn" type="submit">{step.type==="messageContact"?"Send message":"Continue"}</button></form>;
if(step.type==="info")return <><div className="chatPrompt">{step.prompt}</div><div className="contactQuickList"><div><Phone size={14}/><span>+1 (844) 924-3030</span></div><div><Mail size={14}/><span>info@cladcan.ca</span></div><div><MapPin size={14}/><span>5000 Dufferin St, Unit K, North York, ON M3H 5T5</span></div><div><Clock3 size={14}/><span>Business hours: confirm with office</span></div></div><button className="chatActionBtn" onClick={()=>advance({[step.key]:"viewed"})}>Continue</button></>;return null}
return <>{open&&<div className="chatPanel chatPanelLarge" onMouseMove={resetIdle}><div className="chatHead"><div><b>CladCan Project Assistant</b><span>Exterior systems guidance & project support</span></div><button onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="chatBody chatBodyStructured">{screen==="menu"&&<div className="chatScreen"><div className="chatWelcome"><span>PROJECT ASSISTANT</span><b>How can we help with your project?</b></div><div className="mainMenuOptions">{MAIN_MENU.map(i=><button key={i.flow} className={`${i.primary?"primaryMenuItem":""} ${i.priority?"urgentMenuItem":""}`} onClick={()=>startFlow(i.flow)}>{i.priority&&<AlertTriangle size={15}/>}<span>{i.label}</span></button>)}</div></div>}{screen==="services"&&<div className="chatScreen"><button className="chatBack" onClick={mainMenu}><ArrowLeft size={14}/> Main menu</button><div className="chatPrompt">Services We Offer</div><div className="chatInfoText">Material Supply · Fabrication · Installation · Design & Permit Assistance · Repairs · Exterior Systems Consultation</div><button className="chatActionBtn" onClick={()=>startFlow("quote")}>Request a Quote</button></div>}{screen==="technical"&&<div className="chatScreen"><button className="chatBack" onClick={mainMenu}><ArrowLeft size={14}/> Main menu</button><div className="chatPrompt">Technical / General Questions</div><div className="faqList">{TECH_QA.map((x,i)=><details key={i}><summary>{x.q}</summary><p>{x.a}</p></details>)}</div></div>}{screen==="flow"&&flow&&<div className="chatScreen"><div className="flowToolbar"><button className="chatBack" onClick={back}><ArrowLeft size={14}/> Back</button><span>{stepIndex+1} / {flow.steps.length}</span></div>{stepIndex===0&&<div className={`flowIntro ${flow.priority?"urgentIntro":""}`}>{flow.intro}</div>}<div className="flowProgress"><span style={{width:`${((stepIndex+1)/flow.steps.length)*100}%`}}/></div>{renderStep()}</div>}{screen==="done"&&<div className="chatScreen chatDone"><div className="doneIcon">✓</div><h3>Submitted</h3><p>{flow?.final}</p><button className="chatActionBtn" onClick={mainMenu}>Back to Main Menu</button></div>}</div></div>}<button className="chatLauncher" onClick={()=>setOpen(!open)} aria-label="Open CladCan chatbot">{open?<X size={22}/>:<MessageCircle size={22}/>}</button></>}
