import Link from "next/link";
import { ArrowUpRight, Check, Download, FileText, Ruler, Box, Palette } from "lucide-react";
import ProductApplicationNav from "@/components/ProductApplicationNav";
import SystemVisualGallery from "@/components/SystemVisualGallery";
import { getVisuals } from "@/data/visualCatalog";

export default function ProductPage({breadcrumb=[],applicationLinks=[],eyebrow,title,subtitle,intro,images=[],specs=[],benefits=[],applications=[],components=[],finishes=[],resources=[],relatedProducts=[],manufacturer,manufacturerUrl,ctaTitle="Considering this product for your project?",ctaText="Send us your drawings, elevations or project requirements and our team can help review product selection, quantities and installation requirements."}) {
  const pageVisuals = images.length ? images : getVisuals(`${eyebrow} ${title} ${subtitle || ""}`);
  return <main className="productDetailPage">
    <section className="productDetailHero exteriorSystemDetailHero"><div className="exteriorSystemHeroMedia" style={{backgroundImage:`url("${pageVisuals[0]}")`}}/><div className="productDetailHeroOverlay"/><div className="wrap productDetailHeroContent"><span className="productDetailEyebrow">{eyebrow}</span><h1>{title}</h1>{subtitle&&<h2 className="productDetailSubtitle">{subtitle}</h2>}<p>{intro}</p><div className="productDetailHeroActions"><Link href="/contact" className="btn productDetailPrimaryBtn">Request a Quote <ArrowUpRight size={15}/></Link><Link href="/contact" className="btn productDetailSecondaryBtn">Request a Sample</Link></div></div></section>
    <ProductApplicationNav links={applicationLinks}/>
    <section className="productDetailOverview"><div className="wrap productOverviewGrid"><div className="productOverviewCopy"><span className="productDetailEyebrow dark">PRODUCT OVERVIEW</span><h2>Product information<br/>at a glance.</h2><p>{intro}</p>{manufacturer&&<div className="productManufacturer"><span>MANUFACTURER</span>{manufacturerUrl?<a href={manufacturerUrl} target="_blank" rel="noopener noreferrer">{manufacturer}<ArrowUpRight size={13}/></a>:<strong>{manufacturer}</strong>}</div>}</div><div className="productSpecTable">{specs.map(spec=><div key={spec.label}><span>{spec.label}</span><strong>{spec.value}</strong></div>)}</div></div></section>
    {benefits.length>0&&<section className="productDetailBenefits"><div className="wrap"><div className="productDetailSectionHeader light"><span className="productDetailEyebrow">KEY BENEFITS</span><h2>Designed for durable<br/>exterior performance.</h2></div><div className="productBenefitGrid">{benefits.map((benefit,index)=><article key={benefit.title}><span className="productBenefitNumber">{String(index+1).padStart(2,"0")}</span><h3>{benefit.title}</h3><p>{benefit.text}</p></article>)}</div></div></section>}
    {applications.length>0&&<section className="productApplications"><div className="wrap productApplicationsGrid"><div><span className="productDetailEyebrow dark">APPLICATIONS</span><h2>Where this product<br/>fits the project.</h2></div><div className="productApplicationList">{applications.map(item=><div key={item}><Check size={15}/><span>{item}</span></div>)}</div></div></section>}
    {components.length>0&&<section className="productComponents"><div className="wrap"><div className="productDetailSectionHeader"><div><span className="productDetailEyebrow dark">SYSTEM COMPONENTS</span><h2>Profiles, trims<br/>and accessories.</h2></div><p>Final component quantities and accessories should be coordinated with project dimensions, details and installation requirements.</p></div><div className="productComponentsGrid">{components.map((item,index)=><article key={`${item.title}-${index}`}><span>{String(index+1).padStart(2,"0")}</span><h3>{item.title}</h3>{item.detail&&<p>{item.detail}</p>}{item.sku&&<small>SKU: {item.sku}</small>}</article>)}</div></div></section>}
    {finishes.length>0&&<section className="productFinishes"><div className="wrap productFinishesGrid"><div><span className="productDetailEyebrow">COLOURS & FINISHES</span><h2>Architectural finishes<br/>for different design intents.</h2><p>Product and colour availability can change. Confirm current finish availability with CladCan before final specification.</p><Link href="/contact" className="productFinishLink">Request Current Colour Samples <ArrowUpRight size={14}/></Link></div><div className="productFinishList">{finishes.map(finish=><div key={finish}><Palette size={17}/><span>{finish}</span></div>)}</div></div></section>}
    <SystemVisualGallery title={title} images={pageVisuals} />
    {resources.length>0&&<section className="productResources"><div className="wrap"><div className="productDetailSectionHeader"><div><span className="productDetailEyebrow dark">TECHNICAL RESOURCES</span><h2>Documents for design,<br/>specification & installation.</h2></div><p>Manufacturer documents remain the controlling source for current technical information.</p></div><div className="productResourceGrid">{resources.map(resource=>{const Icon=resource.icon==="drawing"?Ruler:resource.icon==="package"?Box:resource.icon==="download"?Download:FileText;return <a href={resource.href} target="_blank" rel="noopener noreferrer" key={resource.title}><Icon size={22}/><div><span>{resource.type}</span><h3>{resource.title}</h3></div><ArrowUpRight size={16}/></a>})}</div></div></section>}
    {relatedProducts.length>0&&<section className="productRelated"><div className="wrap"><div className="productDetailSectionHeader"><div><span className="productDetailEyebrow dark">RELATED PRODUCTS</span><h2>Explore alternatives.</h2></div></div><div className="productRelatedGrid">{relatedProducts.map(product=>product.href?<Link href={product.href} key={product.title} className="productRelatedCard"><span>{product.type}</span><h3>{product.title}</h3><p>{product.description}</p><strong>View Product <ArrowUpRight size={13}/></strong></Link>:<article key={product.title} className="productRelatedCard"><span>{product.type}</span><h3>{product.title}</h3><p>{product.description}</p></article>)}</div></div></section>}
    <section className="productDetailCTA"><div className="wrap productDetailCTAInner"><div><span className="productDetailEyebrow dark">PRODUCT SUPPORT</span><h2>{ctaTitle}</h2><p>{ctaText}</p></div><Link href="/contact" className="btn productDetailPrimaryBtn">Talk to CladCan <ArrowUpRight size={15}/></Link></div></section>
  </main>;
}
