import Link from "next/link";
import { ArrowRight, CheckCircle2, FileText, Layers3, Ruler, Truck, ClipboardCheck, HelpCircle, Users, Building2, PackageCheck } from "lucide-react";

export default function ServiceDetailPage({eyebrow,title,lead,image,summary,deliverables=[],process=[],worksWith=[],projectStages=[],systems=[],coordination=[],quality=[],faqs=[],related=[],note,disclaimer}){
 return <main className="serviceV9 serviceV10">
  <section className="serviceV9Hero"><div className="serviceV9HeroMedia"><img src={image} alt={`${title} by CladCan`} /><div/></div><div className="wrap serviceV9HeroGrid"><div><span>{eyebrow}</span><h1>{title}</h1></div><div><p>{lead}</p><div className="serviceV9HeroActions"><Link href="/contact" className="btn serviceV9Red">Discuss Your Project <ArrowRight size={15}/></Link><Link href="/exterior-systems" className="serviceV9Text">Explore exterior systems <ArrowRight size={13}/></Link></div></div></div></section>
  <section className="serviceV9Statement"><div className="wrap serviceV9StatementGrid"><span>THE ROLE</span><h2>{summary}</h2></div></section>
  <section className="serviceV9Scope"><div className="wrap"><div className="serviceV9Head"><div><span>WHAT WE HANDLE</span><h2>Scope built around the project.</h2></div><p>Final scope depends on drawings, selected systems, site conditions and project requirements. We define responsibilities and deliverables before execution.</p></div><div className="serviceV9Deliverables">{deliverables.map((d,i)=><article key={d.title}><small>{String(i+1).padStart(2,"0")}</small><d.icon size={22}/><h3>{d.title}</h3><p>{d.text}</p>{d.tags&&<div>{d.tags.map(t=><span key={t}>{t}</span>)}</div>}</article>)}</div></div></section>
  {(systems.length>0||projectStages.length>0)&&<section className="serviceV10Matrix"><div className="wrap serviceV10MatrixGrid">{systems.length>0&&<div><span className="serviceV10Label">SYSTEMS WE WORK WITH</span><h2>Connected to the material—not separated from it.</h2><div className="serviceV10Links">{systems.map(s=><Link key={s.href} href={s.href}><span>{s.title}</span><ArrowRight size={13}/></Link>)}</div></div>}{projectStages.length>0&&<div><span className="serviceV10Label">WHEN WE CAN JOIN</span><h2>Support at the stage where it creates value.</h2><div className="serviceV10Stages">{projectStages.map((s,i)=><div key={s.title}><small>{String(i+1).padStart(2,"0")}</small><div><h3>{s.title}</h3><p>{s.text}</p></div></div>)}</div></div>}</div></section>}
  <section className="serviceV9Process"><div className="wrap serviceV9ProcessGrid"><div className="serviceV9ProcessIntro"><span>HOW IT MOVES</span><h2>A clearer path from information to execution.</h2><p>{note||"The workflow is adjusted to the service and project stage, but the principle stays the same: resolve critical information before it becomes a field problem."}</p></div><div className="serviceV9Steps">{process.map((p,i)=><div key={p.title}><b>{String(i+1).padStart(2,"0")}</b><div><h3>{p.title}</h3><p>{p.text}</p></div></div>)}</div></div></section>
  {(coordination.length>0||quality.length>0)&&<section className="serviceV10Coord"><div className="wrap serviceV10CoordGrid"><div><span className="serviceV10Label">PROJECT COORDINATION</span><h2>Interfaces are part of the scope.</h2><p>Exterior work touches structure, waterproofing, openings, roofing, glazing, finishes and other trades. The coordination points matter as much as the individual component.</p><ul>{coordination.map(x=><li key={x}><CheckCircle2 size={15}/><span>{x}</span></li>)}</ul></div><div className="serviceV10Quality"><span className="serviceV10Label">QUALITY & CLOSEOUT</span><h2>Finish the work, then finish the details.</h2><ul>{quality.map(x=><li key={x}><CheckCircle2 size={15}/><span>{x}</span></li>)}</ul>{disclaimer&&<p className="serviceV10Disclaimer">{disclaimer}</p>}</div></div></section>}
  {worksWith.length>0&&<section className="serviceV9For"><div className="wrap"><span>BUILT FOR PROJECT TEAMS</span><div>{worksWith.map((x,i)=><article key={x}><small>0{i+1}</small><h3>{x}</h3></article>)}</div></div></section>}
  {faqs.length>0&&<section className="serviceV10Faq"><div className="wrap"><div className="serviceV9Head"><div><span>COMMON QUESTIONS</span><h2>Useful answers before the first call.</h2></div><p>Project-specific requirements can change the answer. These are starting points for planning the scope.</p></div><div className="serviceV10FaqGrid">{faqs.map((f,i)=><details key={f.q}><summary><span>{String(i+1).padStart(2,"0")}</span>{f.q}<HelpCircle size={16}/></summary><p>{f.a}</p></details>)}</div></div></section>}
  <section className="serviceV9Related"><div className="wrap"><div className="serviceV9Head"><div><span>CONNECTED SERVICES</span><h2>The exterior scope rarely works in isolation.</h2></div></div><div className="serviceV9RelatedGrid">{related.map(r=><Link key={r.href} href={r.href}><small>{r.label}</small><h3>{r.title}</h3><p>{r.text}</p><strong>Explore <ArrowRight size={13}/></strong></Link>)}</div></div></section>
  <section className="serviceV9CTA"><div className="wrap"><div><span>START WITH THE SCOPE</span><h2>Send us what you have.</h2><p>Drawings, elevations, photos, specifications or simply a project description—we can start from the information available and identify the next useful step.</p></div><Link href="/contact" className="btn serviceV9Red">Start a Project <ArrowRight size={15}/></Link></div></section>
 </main>
}
export const serviceIcons={FileText,Layers3,Ruler,Truck,ClipboardCheck,CheckCircle2,Users,Building2,PackageCheck};
