import Link from "next/link";
import { ArrowUpRight, Check, FileText, Box, Ruler, Download } from "lucide-react";
import { longboardApplications, longboardFeaturedProducts } from "@/data/longboard";
import ViewToggleCollection from "@/components/ViewToggleCollection";
export const metadata={title:"Longboard Aluminum Systems | CladCan",description:"Explore Longboard architectural aluminum cladding, siding, soffit, screens and exterior systems available through CladCan."};
export default function LongboardPage(){return <main className="longboardPage">
<section className="longboardHero exteriorSystemDetailHero"><div className="longboardHeroOverlay"/><div className="wrap longboardHeroContent"><span className="longboardEyebrow">LONGBOARD ARCHITECTURAL PRODUCTS</span><h1>Architectural aluminum<br/><em>without compromise.</em></h1><p>High-performance aluminum cladding, siding, soffit and architectural systems combining durable exterior performance with extensive design flexibility.</p><div className="longboardHeroActions"><a href="#longboard-systems" className="btn longboardPrimaryBtn">Explore Systems <ArrowUpRight size={15}/></a><Link href="/contact" className="btn longboardSecondaryBtn">Request a Sample</Link></div></div></section>
<section className="longboardIntro"><div className="wrap longboardIntroGrid"><div><span className="longboardEyebrow dark">LONGBOARD</span><h2>Aluminum engineered<br/>for architecture.</h2></div><div className="longboardIntroCopy"><p>Longboard architectural aluminum systems provide designers, contractors and building owners with a versatile family of exterior products for walls, soffits, siding and architectural features.</p><p>CladCan can coordinate product selection, material supply, fabrication requirements and installation for Longboard exterior systems.</p><div className="longboardChecks"><span><Check size={14}/> Cladding</span><span><Check size={14}/> Siding</span><span><Check size={14}/> Soffit</span><span><Check size={14}/> Screens</span></div></div></div></section>
<section className="longboardSystems" id="longboard-systems"><div className="wrap"><div className="longboardSectionHeader"><div><span className="longboardEyebrow dark">EXTERIOR SYSTEMS</span><h2>Choose by application.</h2></div><p>Explore Longboard systems based on the part of the building envelope or architectural application you are designing.</p></div><ViewToggleCollection items={longboardApplications.map(item=>({number:item.number,title:item.title,description:item.description,href:item.href,tags:item.products,linkLabel:`Explore ${item.title}`}))} /></div></section>
<section className="longboardFeatured"><div className="wrap"><div className="longboardSectionHeader"><div><span className="longboardEyebrow dark">FEATURED PRODUCTS</span><h2>Explore the product family.</h2></div><p>Individual products may support multiple applications. Explore product-specific profiles, finishes, specifications and documentation.</p></div><ViewToggleCollection items={longboardFeaturedProducts.map((product,index)=>({number:String(index+1).padStart(2,"0"),title:product.title,subtitle:product.type,description:product.description,href:product.href,linkLabel:"View Product"}))} /></div></section>
<section className="longboardFinishes"><div className="wrap longboardFinishesGrid"><div><span className="longboardEyebrow">HIGH-PERFORMANCE FINISHES</span><h2>Colour, texture<br/>and lasting performance.</h2></div><div><p>Longboard exterior aluminum products are available in a broad range of architectural finishes, including wood-inspired, solid-colour and specialty options.</p><p>Finish availability varies by product and profile. Contact CladCan to review current colours and samples for your project.</p><Link href="/contact" className="longboardTextLink">Request Finish Samples <ArrowUpRight size={14}/></Link></div></div></section>
<section className="longboardTechnical"><div className="wrap"><div className="longboardTechnicalHeader"><span className="longboardEyebrow dark">TECHNICAL RESOURCES</span><h2>From design development<br/>to installation.</h2></div><div className="longboardTechnicalGrid"><article><FileText size={24}/><h3>Specifications</h3><p>Product-specific technical and specification information for design and procurement.</p></article><article><Ruler size={24}/><h3>Installation Guides</h3><p>Installation documentation for Longboard exterior systems and applications.</p></article><article><Box size={24}/><h3>Submittal Packages</h3><p>Product information organized for architectural review and project submittals.</p></article><article><Download size={24}/><h3>CAD / BIM</h3><p>Product drawings and digital design resources available for selected systems.</p></article></div></div></section>
<section className="longboardCTA"><div className="wrap longboardCTAInner"><div><span className="longboardEyebrow dark">LONGBOARD + CLADCAN</span><h2>Specify the right system<br/>for your project.</h2><p>Send us your elevations, drawings or design requirements and our team can help coordinate Longboard system selection, material supply and installation.</p></div><Link href="/contact" className="btn longboardPrimaryBtn">Talk to CladCan <ArrowUpRight size={15}/></Link></div></section>
</main>}
