import ProductPage from "@/components/ProductPage";
export const metadata={title:"Thermal Clips for Steel Cladding | CladCan",description:"Thermally improved cladding attachment and sub-framing coordination for steel siding, soffit and exterior wall assemblies."};
export default function Page(){return <ProductPage
  eyebrow="STEEL SIDING & SOFFIT"
  title="Thermal Clips"
  subtitle="Support the cladding. Reduce the thermal bridge."
  intro="Thermal clips are attachment components used within exterior sub-framing to carry cladding loads while limiting direct metal-to-structure heat flow. Clip type, spacing, fasteners and girts must be selected around the wall assembly, insulation depth, loads, substrate and the cladding manufacturer’s requirements."
  images={["/images/exterior-systems/fastplank/fastplank-clip-slide-installation-system.webp","/images/content/steel-project.webp","/images/exterior-systems/custom-metal-trims-flashings.jpg"]}
  specs={[{label:"Role",value:"Thermally improved cladding attachment"},{label:"Assembly position",value:"Between substrate and exterior girt or rail"},{label:"Cladding interface",value:"Horizontal or vertical sub-framing, system dependent"},{label:"Design inputs",value:"Loads, substrate, insulation depth and clip spacing"},{label:"Engineering",value:"Project-specific review may be required"},{label:"Coordination",value:"Membranes, insulation, fire stopping, girts and fasteners"}]}
  benefits={[{title:"Reduced thermal bridging",text:"A thermally improved clip can reduce direct conductive paths compared with continuous metal framing."},{title:"Insulation continuity",text:"Clip-and-girt assemblies allow exterior insulation to remain more continuous across the backup wall."},{title:"Adjustable support",text:"Selected systems can help establish a consistent cladding plane over varying substrates and insulation depths."},{title:"Coordinated loads",text:"Engineered attachment layouts transfer wind and dead loads back to the supporting structure."}]}
  applications={["Steel siding attachment over exterior insulation","Commercial rainscreen wall assemblies","Retrofit overcladding and façade renewal","Institutional and multi-family construction","Cladding assemblies requiring thermally improved sub-framing"]}
  components={[{title:"Thermal Clip",detail:"Thermally improved stand-off component selected for the required insulation depth and structural demand."},{title:"Girt or Rail",detail:"Horizontal or vertical framing member that receives the steel cladding attachment."},{title:"Structural Fasteners",detail:"Substrate-specific fasteners transfer clip and cladding loads into the backup wall."},{title:"Exterior Insulation",detail:"Continuous insulation is fitted around the attachment grid in accordance with the assembly design."},{title:"Air / Water Membrane",detail:"Clip penetrations and interfaces must be coordinated to preserve membrane continuity."},{title:"Base & Opening Supports",detail:"Additional framing may be required at starts, corners, openings and other concentrated-load conditions."}]}
  finishes={["Galvanized steel components","Stainless steel options, system dependent","Thermal isolation pads or engineered low-conductivity components","Compatible exterior girts and rails"]}
  relatedProducts={[{type:"STEEL SYSTEM",title:"Exposed Fastener",description:"Corrugated and ribbed steel panels coordinated with the selected sub-framing.",href:"/exterior-systems/steel/exposed-fastener"},{type:"STEEL SYSTEM",title:"Hidden Fastener",description:"Concealed-fastener panels supported by project-specific framing.",href:"/exterior-systems/steel/hidden-fastener"},{type:"CUSTOM METAL",title:"Trims & Flashings",description:"Finish wall perimeters, transitions and openings.",href:"/exterior-systems/steel/trims-flashings"}]}
  ctaText="Share the wall section, insulation thickness, substrate, cladding profile and project location so the attachment strategy can be reviewed with the appropriate manufacturer and project professionals."
/>}
