import CurrentSitePage from "@/components/CurrentSitePage";
export const metadata={title:'Fibre Cement'+" | CladCan",description:'Fibre cement siding combines cement and cellulose fibres to create durable, low-maintenance exterior cladding for many residential and commercial applications.'};
const supportingNotes = [
  {label:"What it is", text:"Fibre cement is a cement-based cladding system commonly used where a project needs a durable exterior with a traditional wood-like appearance and a broad range of profile options."},
  {label:"Where it fits", text:"It is often considered for residential, multi-unit and commercial exteriors where the design calls for enduring siding performance and a product palette that can suit multiple architectural styles."},
  {label:"Selection factors", text:"Profile choice, trim details, fastening layout, weather exposure and the manufacturer’s installation requirements all influence how well the material performs in the field."},
  {label:"How CladCan helps", text:"CladCan can support product comparison, supply coordination, trim and accessory planning, and installation sequencing around the actual project scope."}
];
export default function Page(){return <CurrentSitePage title={'Fibre Cement'} intro={'Fibre cement remains a widely used exterior option for projects that need a durable cladding with a traditional wood-like appearance and a broad range of profile choices.'} overview={'Fibre cement cladding is commonly specified when a project needs a resilient exterior that can support different architectural styles, weather exposure conditions and finish expectations. Product selection should align with the intended profile, detailing and manufacturer installation requirements.'} items={[{title:'James Hardie',href:'/exterior-systems/fibre-cement/james-hardie',text:'Lap siding, panel and trim options used across residential and commercial exterior applications.'},{title:'Nichiha',href:'/exterior-systems/fibre-cement/nichiha',text:'Architectural fibre cement systems with textured finishes and panelized exterior applications.'},{title:'Siding & Panels',href:'/exterior-systems/fibre-cement/siding-panels',text:'Profile and panel options that help balance traditional and contemporary façade expressions.'}]} decisionSupport={supportingNotes} />;}
