import ProductPage from "@/components/ProductPage";
export const metadata={title:"Steel Siding Trims & Flashings | CladCan",description:"Custom steel trims and flashings for siding, soffit, openings, corners, parapets, transitions and cladding terminations."};
export default function Page(){return <ProductPage
  eyebrow="STEEL SIDING & SOFFIT"
  title="Trims & Flashings"
  subtitle="Every edge, opening and transition resolved."
  intro="Trims and flashings complete the visual edges of steel siding and soffit while supporting drainage and weather protection. CladCan coordinates standard accessories and custom-bent profiles from drawings, field dimensions and approved details."
  images={["/images/exterior-systems/custom-metal-trims-flashings.jpg","/images/content/steel-project.webp","/images/content/agway-siding-project.webp"]}
  specs={[{label:"Fabrication",value:"Standard profiles and custom-bent sheet metal"},{label:"Typical locations",value:"Corners, jambs, heads, sills, bases, parapets and transitions"},{label:"Materials",value:"Prefinished steel and compatible project-specific metals"},{label:"Finish",value:"Coordinated with the selected siding or soffit system"},{label:"Inputs",value:"Shop drawings, sketches, approved details or verified dimensions"},{label:"Compatibility",value:"Cladding, membranes, sealants, fasteners and adjacent metals"}]}
  benefits={[{title:"Complete appearance",text:"Coordinated edge profiles create clean, deliberate lines around panels, openings and material transitions."},{title:"Water management",text:"Properly lapped and integrated flashings help direct water outward and preserve drainage paths."},{title:"Custom fabrication",text:"Project-specific profiles can be bent to suit unique geometries and field conditions."},{title:"System coordination",text:"Matching gauges, finishes and interfaces reduce visible inconsistency and avoid last-minute field improvisation."}]}
  applications={["Outside and inside corners","Window and door jambs, heads and sills","Base, starter and termination conditions","Parapet caps and coping flashings","Soffit, fascia and roofline transitions","Transitions between steel and adjacent cladding materials"]}
  components={[{title:"Corner Trims",detail:"Inside and outside profiles finish changes in wall direction and protect panel edges."},{title:"Jamb, Head & Sill Flashings",detail:"Opening profiles coordinate steel cladding with windows, doors and membrane transitions."},{title:"Base & Starter Trims",detail:"Establish the starting line, drainage edge and lower panel termination."},{title:"J-Channels & Closures",detail:"Receive cut panel edges and close compatible perimeter conditions."},{title:"Coping & Parapet Caps",detail:"Custom-formed caps protect horizontal roof and wall terminations."},{title:"Transition Flashings",detail:"Resolve changes between profiles, planes, materials and roof-to-wall interfaces."},{title:"Z-Bars & Hat Channels",detail:"Fabricated support and transition components for project-specific assembly requirements."},{title:"Custom Profiles",detail:"Shop-bent shapes produced from approved dimensions, sketches or shop drawings."}]}
  finishes={["Colour-matched prefinished steel","Perspectra Plus Series colours","Galvanized steel","Custom colour and gauge options","Compatible aluminum or specialty-metal profiles where specified"]}
  relatedProducts={[{type:"STEEL SYSTEM",title:"Exposed Fastener",description:"Coordinate closures and trims with corrugated or ribbed profiles.",href:"/exterior-systems/steel/exposed-fastener"},{type:"STEEL SYSTEM",title:"Hidden Fastener",description:"Match concealed-fastener siding and soffit edges.",href:"/exterior-systems/steel/hidden-fastener"},{type:"ATTACHMENT",title:"Thermal Clips",description:"Coordinate perimeter framing with the thermal attachment layout.",href:"/exterior-systems/steel/thermal-clips"}]}
/>}
