import ProductPage from "@/components/ProductPage";
import { steelTechnicalSections } from "@/data/steelProductSupport";
export const metadata={title:"Hidden Fastener Steel Siding & Soffit | CladCan",description:"Explore HF-12, HF-8, Decorative, Stratus, Galanta and Moderno concealed-fastener steel siding and soffit systems."};
export default function Page(){return <ProductPage
  eyebrow="STEEL SIDING & SOFFIT"
  title="Hidden Fastener"
  subtitle="Clean lines with concealed attachment."
  intro="Hidden-fastener steel systems conceal attachment points behind panel joints or locking edges, producing a refined uninterrupted surface. The category includes linear, board-and-batten, wood-look and vented soffit options for residential, commercial, industrial and institutional design."
  images={["/images/content/agway-siding-project.webp","/images/content/steel-project.webp","/images/content/system-steel.webp"]}
  specs={[{label:"Fastening",value:"Concealed screw slots or interlocking attachment edges"},{label:"Primary profiles",value:"HF-12, HF-8, Decorative, Stratus, Galanta and Moderno"},{label:"Applications",value:"Walls, accents, fascia and soffits"},{label:"Orientation",value:"Vertical or horizontal, product dependent"},{label:"Soffit options",value:"Vented and non-vented formats, product dependent"},{label:"Finish families",value:"Solid, greyscale, textured and wood-look selections"}]}
  benefits={[{title:"Refined appearance",text:"Concealed screws preserve continuous panel lines and minimize visual interruption."},{title:"Broad design range",text:"Linear, batten, flat and wood-look formats support contemporary and traditional architecture."},{title:"Siding and soffit",text:"Selected profiles are available in wall, fascia and ventilated or non-ventilated soffit configurations."},{title:"Durable steel",text:"Prefinished steel provides long-lasting colour, weather resistance and low routine maintenance."}]}
  applications={["Custom homes and residential renovations","Commercial and institutional façades","Horizontal or vertical feature walls","Fascia, canopies and soffits","Interior architectural accent applications where approved"]}
  components={[{title:"HF-12",detail:"Twelve-inch concealed-fastener panel for smooth modern institutional, industrial and commercial surfaces."},{title:"HF-8",detail:"Twelve-inch panel with a four-inch return that creates a distinct board-and-batten expression."},{title:"Decorative Hidden Fastener",detail:"Custom-length wall, fascia and soffit panel offered in vented round-hole, slotted-hole and non-vented formats."},{title:"Stratus",detail:"Twenty-six-gauge concealed-fastener cladding for vertical or horizontal walls, accents and soffits; source content lists custom lengths from 12 to 384 inches."},{title:"Galanta",detail:"Six-and-one-quarter-inch-wide wood-textured steel siding and soffit with end-notched overlapping panels and vertical or horizontal installation."},{title:"Moderno",detail:"Twenty-six-gauge G90 galvanized steel wood-look panels in standard twelve-foot lengths with matching accessories and vented soffit options."},{title:"Matching Trims",detail:"Coordinated starters, corners, channels, closures and termination profiles complete each selected system."},{title:"Vented Soffit",detail:"Product-specific perforation options support required roof and soffit ventilation strategies."}]}
  technicalSections={steelTechnicalSections}
  finishes={["Solid colour series","Greyscale series","Wood Shade series","Galanta classic and shaded woodgrain","Perspectra Plus Series SMP finishes","Kynar 500 / PVDF options, product dependent","Coastal finish solutions, product dependent"]}
  relatedProducts={[{type:"STEEL SYSTEM",title:"Exposed Fastener",description:"Efficient corrugated and ribbed profiles with visible attachment.",href:"/exterior-systems/steel/exposed-fastener"}]}
/>}
