import { Hero, ArchitecturalVisual, SectionHeading, CTA } from "@/components/SiteBlocks";
export const metadata={title:"Architectural ACM Panels"};
export default function ACM(){
 return <>
  <Hero eyebrow="EXTERIOR SYSTEMS · ARCHITECTURAL METAL" title="Architectural ACM panel systems." copy="Lightweight, precise and highly adaptable façade packages supported by material coordination, project-specific fabrication and professional installation." primary="Request Project Pricing" secondary={{label:"Request Sample",href:"/contact"}}><ArchitecturalVisual label="ACM FAÇADE PROJECT"/></Hero>
  <section className="section"><div className="wrap"><SectionHeading eyebrow="SYSTEM OVERVIEW" title="Designed for clean geometry and controlled detailing." copy="ACM is widely used where panel flatness, crisp joints, finish selection and custom fabrication are central to the architectural expression."/>
  <div className="benefitGrid">{["Fabrication flexibility","Architectural finish range","Large-format visual fields","Custom trims & transitions","Coordinated panel kits","Supply-to-install scope"].map((x,i)=><div key={x}><span>0{i+1}</span><h3>{x}</h3><p>{["Panels can be cut, routed and formed around project-specific modules.","Finish availability varies by manufacturer and specification.","Well suited to contemporary commercial and residential façade compositions.","Corners, closures and transitions can be coordinated with the panel system.","Fabricated output can be identified and packaged around field sequence.","Material, fabrication and installation can be managed under one exterior scope."][i]}</p></div>)}</div></div></section>
  <section className="section paper"><div className="wrap technicalGrid"><div><span className="eyebrow">TECHNICAL INFORMATION</span><h2>Specify the exact system.</h2><p>Fire classification, core, finish, warranty, allowable dimensions and performance requirements vary by manufacturer and assembly. The production website should never publish generic technical claims as if they apply to every ACM system.</p><div className="warningBox">Technical values will be populated only from verified current manufacturer data sheets.</div></div><div className="specTable">{["Manufacturer","Panel thickness","Core / fire classification","Finish system","Panel module","Sub-framing","Warranty","Project engineering"].map(x=><div key={x}><span>{x}</span><b>Project / manufacturer specific</b></div>)}</div></div></section>
  <section className="section"><div className="wrap"><SectionHeading eyebrow="RELATED WORK" title="See ACM in context."/><div className="imageMosaic"><ArchitecturalVisual label="COMMERCIAL ACM"/><ArchitecturalVisual label="DETAIL + JOINT" tone="warm"/><ArchitecturalVisual label="FABRICATED PANEL" tone="dark"/></div></div></section>
  <CTA/>
 </>;
}
