import CurrentSitePage from "@/components/CurrentSitePage";
export const metadata={title:'WPC (Wood Plastic Composite)'+" | CladCan",description:'WPC combines wood fibres with thermoplastics to create durable, low-maintenance architectural products for siding, soffit and accent applications.'};
const supportingNotes = [
  {label:"What it is", text:"WPC products are composite profiles that combine wood fibre and thermoplastic materials to create dimensional architectural products with a wood-like appearance and a lower-maintenance service profile."},
  {label:"Where it fits", text:"They are often considered for wall cladding, soffits, fluted applications, trim accents and privacy screens where a wood aesthetic is desired with less routine material upkeep."},
  {label:"Selection factors", text:"Profile style, finish expectations, expansion and contraction behaviour, attachment strategy and how the system meets adjacent materials should all be reviewed before the material is specified."},
  {label:"How CladCan helps", text:"CladCan can support profile selection, accessory coordination and installation planning so the design intent aligns with the actual assembly and site conditions."}
];
export default function Page(){return <CurrentSitePage title={'WPC (Wood Plastic Composite)'} intro={'WPC combines wood fibres with thermoplastics to create durable, low-maintenance architectural products for siding, soffit and accent applications.'} overview={'WPC options are often evaluated when a project wants the warmth of wood without the same maintenance profile, but the final decision still depends on profile, detailing, attachment and project conditions.'} items={[{title:'WPC Beams',href:'/exterior-systems/wpc/beams',text:'Composite architectural beams suited to privacy screens, louvers and dimensional accents.'},{title:'Fluted Siding & Soffit',href:'/exterior-systems/wpc/fluted-siding-soffit',text:'Fluted profiles add rhythm, texture and depth to wall and soffit design.'},{title:'Shiplap Siding',href:'/exterior-systems/wpc/shiplap-siding',text:'Overlapping shiplap profiles provide a clean linear appearance for exterior applications.'}]} decisionSupport={supportingNotes} />;}
